name: Build Main

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 23:26:00 UTC (Monday at 15:26:00 PST)
    # We offset from the hour and half hour to go easy on the servers :)
    - cron: '26 23 * * 1'

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          pkg-config \
          ffmpeg \
          libavformat-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libswresample-dev

    - name: Install Python Dependencies
      run: |
        cd python/
        echo "Cython<3" > /tmp/pip-constraints.txt
        PIP_CONSTRAINT=/tmp/pip-constraints.txt PIP_BUILD_CONSTRAINT=/tmp/pip-constraints.txt pip install .[test]
    - name: Lint and Format Python
      run: |
        cd python/
        flake8 cdp_richmond_(in)_backend --count --verbose --show-source --statistics
        black --check cdp_richmond_(in)_backend

  build-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install Web App Dependencies
      run: |
        cd web/
        npm i
    - name: Build Web App
      run: |
        cd web/
        npm run build

