name: Process Special Event

on:
  workflow_dispatch:
    inputs:
      event-details-json-string:
        description: "Event details (see EventIngestionModel in cdp-backend) in JSON string form. The string must be free of any newline or tab characters."
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy-runner-on-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup CML
        uses: iterative/setup-cml@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          cml runner \
            --single \
            --labels=gcp-cdp-runner \
            --cloud=gcp \
            --cloud-region=us-west1-b \
            --cloud-image=ubuntu-os-cloud/ubuntu-2204-lts \
            --cloud-type=n1-standard-4 \
            --cloud-gpu=nvidia-tesla-t4 \
            --cloud-spot \
            --cloud-hdd-size=30 \
            --idle-timeout=600

  process-events:
    needs: [deploy-runner-on-gcp]
    runs-on: [self-hosted, gcp-cdp-runner]
    container:
      image: ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Check GPU Drivers
      run: |
        nvidia-smi

    - name: Install Packages
      run: |
        sudo apt update
        sudo apt-get install -y --no-install-recommends \
          pkg-config \
          libsndfile1 \
          libavformat-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libswresample-dev \
          ffmpeg

    - name: Install Python Dependencies
      run: |
        cd python/
        echo "Cython<3" > ci-constraints.txt
        pip install --upgrade pip
        PIP_CONSTRAINT=ci-constraints.txt pip install .

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: cdp-richmond-in-jvrzndvq

    - name: Dump Credentials to JSON
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google-creds.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "python/"

    - name: Dump Event Details to JSON
      run: |
        echo ${{ github.event.inputs.event-details-json-string }} > python/event-details.json

    - name: Process special events into event gather pipeline
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        cd python/
        process_special_event \
          --event_details_file event-details.json \
          --event_gather_config_file event-gather-config.json

