name: Run Command

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      command-and-args:
        description: "A command and all arguments to passthrough to the runner."
        required: true

jobs:
  run-command:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          pkg-config \
          ffmpeg \
          libavformat-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavutil-dev \
          libavfilter-dev \
          libswscale-dev \
          libswresample-dev

    - name: Install Python Dependencies
      run: |
        cd python/
        echo "Cython<3" > /tmp/pip-constraints.txt
        PIP_CONSTRAINT=/tmp/pip-constraints.txt PIP_BUILD_CONSTRAINT=/tmp/pip-constraints.txt pip install .

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v3
      with:
        project_id: cdp-richmond-in-jvrzndvq

    - name: Dump Credentials to JSON
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: "google-creds.json"
        json: ${{ secrets.GOOGLE_CREDENTIALS }}
        dir: "python/"
    
    - name: Run Command
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        cd python/
        ${{ github.event.inputs.command-and-args }}

